# UI configuration for the 5" IPS touchscreen

[mqtt]
url = "mqtt://tars:pass@127.0.0.1:1883"

[ui]
width = 480
height = 800
fps = 30
num_bars = 64
font = "Arial"
fullscreen = true

[layout]
file = "layout.json"
rotation = 270

[topics]
audio = "stt/audio_fft"
partial = "stt/partial"
final = "stt/final"
tts = "tts/status"

[fft_ws]
enabled = true
url = "ws://stt:8765/fft"
retry_seconds = 5.0
