[project]
name = "tars-router"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "asyncio-mqtt>=0.16.2",
  "orjson>=3.10.7",
  "uvloop>=0.19.0; platform_system != 'Windows'",
  "paho-mqtt<2.0",
]

[tool.ruff]
line-length = 100
