services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: tars-mqtt
    network_mode: host
    env_file: .env
    volumes:
      - ./ops:/ops:ro
      - ./ops/mosquitto-data:/mosquitto/data
      - ./ops/mosquitto-config:/mosquitto/config
    entrypoint: ["/bin/sh","-c"]
    command:
      - >
        set -e;
        mkdir -p /mosquitto/data;
        mkdir -p /mosquitto/config;
        if [ ! -f /mosquitto/config/mosquitto.conf ]; then
          cp /ops/mosquitto.conf /mosquitto/config/mosquitto.conf;
        fi;
        if [ ! -f /mosquitto/config/passwd ]; then
          if [ -n "$MQTT_USER" ] && [ -n "$MQTT_PASS" ]; then
            mosquitto_passwd -b -c /mosquitto/config/passwd "$MQTT_USER" "$MQTT_PASS";
            echo 'Generated passwd file';
          else
            echo 'WARNING: MQTT_USER/PASS not set; creating anonymous passwd placeholder';
            touch /mosquitto/config/passwd;
          fi;
        fi;
        exec /docker-entrypoint.sh mosquitto -c /mosquitto/config/mosquitto.conf

  stt:
    build: ./apps/stt-worker
    container_name: tars-stt
    network_mode: host
    env_file: .env
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
      - ./models/whisper:/host-models
    environment:
      - MQTT_URL=mqtt://$MQTT_USER:$MQTT_PASS@$MQTT_HOST:$MQTT_PORT
      - WHISPER_MODEL=${WHISPER_MODEL:-small}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - STT_BACKEND=${STT_BACKEND:-whisper}
      - WS_URL=${WS_URL:-ws://127.0.0.1:9000/stt}
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - SILENCE_THRESHOLD_MS=${SILENCE_THRESHOLD_MS:-600}
      - CHUNK_DURATION_MS=${CHUNK_DURATION_MS:-20}
      - VAD_AGGRESSIVENESS=${VAD_AGGRESSIVENESS:-3}
      - SAMPLE_RATE=${SAMPLE_RATE:-16000}

  router:
    build: ./apps/router
    container_name: tars-router
    network_mode: host
    env_file: .env
    environment:
      - MQTT_URL=mqtt://$MQTT_USER:$MQTT_PASS@$MQTT_HOST:$MQTT_PORT
      - PROFILE=offline_fast
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

  tts:
    build: ./apps/tts-worker
    container_name: tars-tts
    network_mode: host
    env_file: .env
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./apps/tts-worker/voices:/voice-models:ro
      - /run/user/1000/pulse:/run/user/1000/pulse:ro
    environment:
      - MQTT_URL=mqtt://$MQTT_USER:$MQTT_PASS@$MQTT_HOST:$MQTT_PORT
      - PIPER_VOICE=/voices/TARS.onnx
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TTS_STREAMING=${TTS_STREAMING:-0}
      - TTS_PIPELINE=${TTS_PIPELINE:-1}

  ui:
    build: ./apps/ui
    container_name: tars-ui
    network_mode: host
    profiles: ["pygame"]
    environment:
      - MQTT_URL=mqtt://$MQTT_USER:$MQTT_PASS@$MQTT_HOST:$MQTT_PORT
      - UI_CONFIG=/config/ui.toml
      - DISPLAY=${DISPLAY}
      - SDL_VIDEODRIVER=x11
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./apps/ui/ui.toml:/config/ui.toml:ro

  ui-web:
    build: ./apps/ui-web
    container_name: tars-ui-web
    network_mode: host
    environment:
      - MQTT_URL=mqtt://$MQTT_USER:$MQTT_PASS@$MQTT_HOST:$MQTT_PORT
    depends_on:
      - mqtt
    restart: unless-stopped
