"""
WiFi Configuration for TARS Servo Controller
Auto-generated by configure_wifi.sh
"""

# WiFi Credentials
WIFI_SSID = "SpectrumSetup-0008"
WIFI_PASSWORD = "helpfulratio546"

# Web Server Configuration
WEB_PORT = 80
WEB_TIMEOUT = 30  # seconds

# Access Point Mode (fallback if WiFi connection fails)
AP_SSID = "TARS-Servo"
AP_PASSWORD = "tars1234"
AP_ENABLED = True  # Set to False to disable AP fallback
