version: "3.8"

services:
  stt-ws:
    build:
      context: ..
      dockerfile: docker/specialized/stt-ws.Dockerfile
    container_name: tars-stt-ws
    network_mode: host
    env_file: .env
    environment:
      # Faster-Whisper model & device selection
      - WHISPER_MODEL=${WHISPER_MODEL:-small}
      - DEVICE=${DEVICE:-auto}
      - COMPUTE_TYPE=${COMPUTE_TYPE:-auto}
      # Partial emission cadence and model cache dir
      - PARTIAL_INTERVAL_MS=${PARTIAL_INTERVAL_MS:-300}
      - MODELS_DIR=/models
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # For older setups on Jetson, uncomment the following line
    # runtime: nvidia
    restart: unless-stopped
    volumes:
      - ./models-cache:/models
