# NPU Override Configuration for TARS Stack
# This file overrides the default wake-activation service to enable NPU acceleration
# 
# Usage:
#   docker compose -f ops/compose.yml -f ops/compose.npu.yml up
#
# Requirements:
#   - RK3588-based device (Orange Pi 5 Max, Rock 5B, etc.)
#   - NPU drivers installed (/dev/rknpu device available)
#   - RKNN model converted (hey_tars.rknn)
#   - NPU runtime libraries (librknnrt.so)

name: tars-stack

services:
  # Override the default wake-activation service for NPU acceleration
  wake-activation:
    # Use NPU-enabled Dockerfile
    build:
      context: ..
      dockerfile: apps/wake-activation/Dockerfile.npu
    image: tars/wake-activation:npu
    container_name: tars-wake-activation-npu
    user: "0:0"  # Run as root to access audio fan-out socket
    privileged: true  # Required for NPU device access
    group_add:
      - "992"  # render group for NPU access
    devices:
      - "/dev/rknpu:/dev/rknpu"
      - "/dev/dri:/dev/dri" 
      - "/dev/mali0:/dev/mali0"
    environment:
      # Disable NPU for wake detection (requires mel preprocessing, not worth complexity)
      # CPU wake detection is fast enough (<5ms per frame)
      WAKE_USE_NPU: 0
      # WAKE_RKNN_MODEL_PATH: ${WAKE_RKNN_MODEL_PATH:-/models/openwakeword/hey_tars.rknn}
      # WAKE_NPU_CORE_MASK: ${WAKE_NPU_CORE_MASK:-0}
      # RKNN_LOG_LEVEL: ${RKNN_LOG_LEVEL:-3}
      # Keep all other environment variables from base service
      MQTT_URL: mqtt://mqtt:1883
      MQTT_HOST: mqtt
      MQTT_PORT: "1883"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      WAKE_AUDIO_FANOUT: ${WAKE_AUDIO_FANOUT:-/tmp/tars/audio-fanout.sock}
      WAKE_MODEL_PATH: ${WAKE_MODEL_PATH:-/models/openwakeword/hey_tars.tflite}
      WAKE_DETECTION_THRESHOLD: ${WAKE_DETECTION_THRESHOLD:-0.35}
      WAKE_MIN_RETRIGGER_SEC: ${WAKE_MIN_RETRIGGER_SEC:-0.8}
      WAKE_SPEEX_NOISE_SUPPRESSION: ${WAKE_SPEEX_NOISE_SUPPRESSION:-1}
      WAKE_VAD_THRESHOLD: ${WAKE_VAD_THRESHOLD:-0.3}
      WAKE_ENERGY_BOOST_FACTOR: ${WAKE_ENERGY_BOOST_FACTOR:-1.2}
      WAKE_LOW_ENERGY_THRESHOLD_FACTOR: ${WAKE_LOW_ENERGY_THRESHOLD_FACTOR:-0.7}
      WAKE_BACKGROUND_NOISE_SENSITIVITY: ${WAKE_BACKGROUND_NOISE_SENSITIVITY:-1}
      WAKE_WAIT_FOR_STT_HEALTH: ${WAKE_WAIT_FOR_STT_HEALTH:-1}
      WAKE_STT_HEALTH_TIMEOUT_SEC: ${WAKE_STT_HEALTH_TIMEOUT_SEC:-30}
      PYTHONPATH: /workspace/apps/wake-activation
    # Add NPU-specific volume mounts
    volumes:
      # Base volumes from original service
      - ../models/openwakeword:/models/openwakeword:ro
      - wake-cache:/tmp/tars
      - ..:/workspace:ro
      # NPU-specific mounts
      - "/dev/dri/renderD129:/dev/dri/renderD129"
      - "/proc/device-tree/compatible:/proc/device-tree/compatible:ro"
      - "/usr/lib/librknnrt.so:/usr/lib/librknnrt.so:ro"

  # Config manager and Litestream don't need NPU overrides
  # They use the base definitions from compose.yml
    # Updated command to indicate NPU mode
    command: ["echo 'NPU Wake activation: Waiting for STT service to stabilize...'; sleep 3; echo 'NPU Wake activation: Starting NPU-accelerated wake word detection'; exec python -m wake_activation"]
    # NPU-specific health check
    healthcheck:
      test: ["CMD", "python", "-c", "from wake_activation.npu_utils import check_npu_availability; exit(0 if check_npu_availability()[0] else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Override the memory service for NPU-accelerated embeddings
  memory:
    build:
      args:
        NPU_EMBEDDER_ENABLED: 1
    container_name: tars-memory-npu
    privileged: true  # Required for NPU device access
    group_add:
      - "992"  # render group for NPU access
    devices:
      - "/dev/rknpu:/dev/rknpu"
      - "/dev/dri:/dev/dri"
      - "/dev/mali0:/dev/mali0"
    environment:
      # Override to enable NPU
      NPU_EMBEDDER_ENABLED: 1
      RKNN_EMBEDDER_PATH: ${RKNN_EMBEDDER_PATH:-/data/model_cache/embedder/all-MiniLM-L6-v2.rknn}
      NPU_CORE_MASK: ${NPU_CORE_MASK:-0}
      NPU_FALLBACK_CPU: ${NPU_FALLBACK_CPU:-1}
      # Keep all other environment variables from base service
      MQTT_URL: mqtt://mqtt:1883
      MQTT_HOST: mqtt
      MQTT_PORT: "1883"
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      MEMORY_DIR: /data
      MEMORY_FILE: memory.pickle.gz
      CHARACTER_NAME: ${CHARACTER_NAME:-TARS}
      CHARACTER_DIR: /config/characters
      EMBED_MODEL: ${EMBED_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
      RAG_STRATEGY: ${RAG_STRATEGY:-hybrid}
      MEMORY_TOP_K: ${MEMORY_TOP_K:-5}
      PYTHONPATH: /workspace/apps/memory-worker/src:/workspace/packages/tars-core/src
    # Add NPU-specific volume mounts
    volumes:
      # Base volumes from original service
      - ../data/memory:/data
      - ../data/model_cache:/data/model_cache
      - ../apps/memory-worker/characters:/config/characters:ro
      - ..:/workspace:ro
      # NPU-specific mounts
      - "/dev/dri/renderD129:/dev/dri/renderD129"
      - "/proc/device-tree/compatible:/proc/device-tree/compatible:ro"
      - "/usr/lib/librknnrt.so:/usr/lib/librknnrt.so:ro"